# Generated by Django 5.2.8 on 2025-12-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='09111001010', max_length=11, unique=True),
            preserve_default=False,
        ),
    ]
