# Generated by Django 5.2.8 on 2025-12-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot_order',
            name='product',
            field=models.CharField(choices=[('naghd-farda', 'naghd-farda'), ('naghd-pasfarda', 'naghd-pasfarda')], default='naghd-farda', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bot_order',
            name='side',
            field=models.CharField(choices=[('buy', ' buy'), ('sell', 'sell')], max_length=10),
        ),
    ]
