# Generated by Django 5.2.8 on 2025-12-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_bot_order_product_alter_bot_order_side'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot_order',
            name='status',
            field=models.CharField(choices=[('send', ' send'), ('expired', 'expired'), ('pending', 'pending')], max_length=10),
        ),
    ]
