# Generated by Django 5.2.8 on 2025-12-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_bot_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot_order',
            name='status',
            field=models.CharField(choices=[('send', ' send'), ('expired', 'expired'), ('pending', 'pending'), ('canceled', 'canceled')], max_length=10),
        ),
    ]
